args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.140453742638513'
  R2: '0.29283560322777136'
  RMSE: '1.262896334206153'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 4
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.35092167648192'
  R2: '0.016648922020829238'
  RMSE: '1.4892301087413817'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 128
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.1856683442062936'
  R2: '0.20221859014447485'
  RMSE: '1.3413727054165827'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 512
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.1989707750047227'
  R2: '0.13793447124680236'
  RMSE: '1.3943687745809794'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.140453742638513'
  R2: '0.29283560322777136'
  RMSE: '1.262896334206153'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 200
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.1535680137378295'
  R2: '0.27222653355019366'
  RMSE: '1.2811666287971661'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: true
upper bound of prediction:
  MAE: '1.3808041506994828'
  R2: '-0.23058556933741614'
  RMSE: '1.6659555817583007'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.140453742638513'
  R2: '0.29283560322777136'
  RMSE: '1.262896334206153'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
upper bound of prediction:
  MAE: '1.1872912714200696'
  R2: '0.20841443399146709'
  RMSE: '1.3361537725856758'
