name: predict_HAT
channels:
  - conda-forge
  - defaults
  - dglteam
  - https://repo.anaconda.com/pkgs/free
  - pytorch
dependencies:
  - libunistring=0.9.10
  - nss=3.69
  - oauthlib=3.2.0
  - libxkbcommon=1.0.3
  - nspr=4.32
  - libbrotlienc=1.0.9
  - gmp=6.2.1
  - olefile=0.46
  - intel-openmp=2021.4.0
  - libtiff=4.2.0
  - dgl-cuda11.1
  - libuv=1.40.0
  - nettle=3.7.3
  - libwebp=1.2.0
  - idna=3.3
  - markdown=3.3.6
  - scipy=1.7.1
  - bzip2=1.0.8
  - sqlalchemy=1.4.26
  - greenlet=1.1.2
  - expat=2.4.1
  - libbrotlicommon=1.0.9
  - giflib=5.2.1
  - pyqt5-sip=4.19.18
  - xorg-kbproto=1.0.7
  - libcblas=3.9.0
  - xorg-libxext=1.3.4
  - zlib=1.2.11
  - cairo=1.16.0
  - pycairo=1.20.1
  - zstd=1.4.9
  - c-ares=1.18.1
  - glib=2.68.4
  - icu=68.2
  - libiconv=1.16
  - pytorch::pytorch[version='1.10.0.*,1.10.0.*']
  - yarl=1.7.2
  - jpeg=9d
  - pytz=2021.3
  - llvm-openmp=12.0.1
  - tensorboard-data-server=0.6.0
  - libclang=11.1.0
  - libstdcxx-ng=11.2.0
  - tornado=6.1
  - xorg-libice=1.0.10
  - multidict=6.0.2
  - tbb=2021.4.0
  - fontconfig=2.13.1
  - ncurses=6.3
  - typing-extensions=4.1.1
  - python=3.9.7
  - libxml2=2.9.12
  - qt=5.12.9
  - boost-cpp=1.74.0
  - libtasn1=4.16.0
  - cycler=0.10.0
  - tensorboard=2.8.0
  - colorama=0.4.4
  - ffmpeg=4.3
  - typing_extensions=4.1.1
  - blinker=1.4
  - pip=21.2.4
  - libbrotlidec=1.0.9
  - numpy=1.21.2
  - rdkit=2021.09.2
  - libgomp=11.2.0
  - click=8.0.4
  - libogg=1.3.4
  - libvorbis=1.3.7
  - cachetools=5.0.0
  - ipykernel=6.0
  - urllib3=1.26.9
  - charset-normalizer=2.0.12
  - certifi=2021.10.8
  - tensorboard-plugin-wit=1.8.1
  - cryptography=36.0.2
  - pysocks=1.7.1
  - libpng=1.6.37
  - pyasn1-modules=0.2.7
  - xorg-libx11=1.7.2
  - pyparsing=3.0.4
  - importlib-metadata=4.11.3
  - libpq=13.3
  - _libgcc_mutex=0.1
  - pyqtchart=5.12
  - pcre=8.45
  - numpy-base=1.21.2
  - google-auth-oauthlib=0.4.6
  - pyopenssl=22.0.0
  - wheel=0.37.0
  - libidn2=2.3.2
  - requests-oauthlib=1.3.1
  - alsa-lib=1.2.3
  - python_abi=3.9
  - libedit=3.1.20210910
  - joblib=1.1.0
  - brotlipy=0.7.0
  - libgfortran-ng=7.5.0
  - pyasn1=0.4.8
  - xorg-xproto=7.0.31
  - xorg-xextproto=7.3.0
  - mysql-libs=8.0.25
  - pytorch-lightning=1.4
  - gst-plugins-base=1.18.5
  - mysql-common=8.0.25
  - munkres=1.1.4
  - nb_conda_kernels=2.3
  - protobuf=3.19.4
  - kiwisolver=1.3.1
  - brotli-bin=1.0.9
  - numexpr=2.7.3
  - xorg-libxrender=0.9.10
  - requests=2.27.1
  - pytorch-mutex=1.0
  - xorg-renderproto=0.11.1
  - aiosignal=1.2.0
  - pycparser=2.21
  - libgfortran4=7.5.0
  - mkl_random=1.2.2
  - krb5=1.19.2
  - frozenlist=1.3.0
  - hyperopt
  - async-timeout=4.0.2
  - mkl_fft=1.3.1
  - readline=8.1
  - mkl=2021.4.0
  - lz4-c=1.9.3
  - fonttools=4.25.0
  - six=1.16.0
  - ca-certificates=2021.10.8
  - zipp=3.7.0
  - openh264=2.1.0
  - cffi=1.15.0
  - pytorch::torchvision=0.11.1
  - sip=4.19.13
  - lcms2=2.12
  - torchmetrics=0.6
  - matplotlib=3.4.3
  - pyqtwebengine=5.12.1
  - cudatoolkit=11.3.1
  - pixman=0.40.0
  - aiohttp=3.8.1
  - reportlab=3.5.68
  - setuptools=58.0.4
  - libuuid=1.0.3
  - boost=1.74.0
  - libprotobuf=3.19.4
  - sqlite=3.36.0
  - mkl-service=2.4.0
  - google-auth=2.6.2
  - pyqt=5.12.3
  - libglib=2.68.4
  - libopus=1.3.1
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - libzlib=1.2.11
  - conda-minify=0.1
  - torchaudio=0.10.0
  - pyqt-impl=5.12.3
  - grpcio=1.44.0
  - ld_impl_linux-64=2.35.1
  - seaborn=0.11
  - xz=5.2.5
  - scikit-learn=1.0.1
  - blas=1.0
  - matplotlib-base=3.4.3
  - libblas=3.9.0
  - glib-tools=2.68.4
  - gstreamer=1.18.5
  - werkzeug=2.0.3
  - _openmp_mutex=4.5
  - xorg-libsm=1.2.2
  - libwebp-base=1.2.0
  - pyjwt=2.3.0
  - pillow=8.4.0
  - brotli=1.0.9
  - gettext=0.19.8.1
  - tqdm=4.62.3
  - libevent=2.1.10
  - freetype=2.11.0
  - libxcb=1.14
  - python-dateutil=2.8.2
  - libffi=3.3
  - libgcc-ng=11.2.0
  - gnutls=3.6.15
  - rsa=4.8
  - tzdata=2021e
  - attrs=21.4.0
  - bottleneck=1.3.2
  - dbus=1.13.18
  - absl-py=1.0.0
  - pandas=1.3.4
  - pyu2f=0.1.5
  - openssl=1.1.1l
  - lame=3.100
  - libllvm11=11.1.0
