10-fold cross-validation results:
  MAE: '4.9698520541790625'
  R2: '0.12326838812686192'
  RMSE: '6.620102426932905'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad2_hidden
  - rad_atom2_hidden
  hidden_size: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.3953721409223467'
  R2: '0.7728223174033422'
  RMSE: '3.3467170003083817'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size: 1024
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.487546917617271'
  R2: '0.7599733002448864'
  RMSE: '3.435925127944393'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size: 230
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.419086466684642'
  R2: '0.7740024858359424'
  RMSE: '3.3420550451030104'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 1024
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4035922795231395'
  R2: '0.7731675386456278'
  RMSE: '3.3456210510534823'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 1024
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.5189744447971147'
  R2: '0.7605085359187633'
  RMSE: '3.4448924336171'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.5333394378644636'
  R2: '0.7579901818867978'
  RMSE: '3.4608487706011366'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 128
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.5142598369333364'
  R2: '0.7600807740089083'
  RMSE: '3.4483609400059487'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 256
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4875191635869056'
  R2: '0.7655945920768351'
  RMSE: '3.405822301826164'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 512
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.470319985156692'
  R2: '0.7683422970701901'
  RMSE: '3.3871592876026155'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 768
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4575207141547413'
  R2: '0.7696673291112649'
  RMSE: '3.3772473426919083'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 1024
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4619575997415004'
  R2: '0.7688786216647806'
  RMSE: '3.3828649320870925'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 1536
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4599134401218974'
  R2: '0.7692352150916826'
  RMSE: '3.3797898868729797'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 2048
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.482318221075887'
  R2: '0.7658650504298061'
  RMSE: '3.4011629307570908'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 128
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.479717762522646'
  R2: '0.7664390562217764'
  RMSE: '3.399800402952588'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 256
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4402760228689706'
  R2: '0.7709805138782635'
  RMSE: '3.366128861144669'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 512
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4310603935397475'
  R2: '0.7733694480091329'
  RMSE: '3.347479386340602'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 768
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '2.4286631061502897'
  R2: '0.7734046382246899'
  RMSE: '3.3493491405539353'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size_M1: 1200
  hidden_size_M2: 1024
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
