10-fold cross-validation results:
  MAE: '1.0078384666007516'
  R2: '0.8008120781531101'
  RMSE: '1.2288198351110664'
args:
  dropout: 0.0
  hidden_size: 1024
  layers: 0
  lr: 0.0277
10-fold cross-validation results:
  MAE: '1.0078384666007516'
  R2: '0.8008120781531101'
  RMSE: '1.2288198351110664'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size: 1024
  layers: 0
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: false
10-fold cross-validation results:
  MAE: '1.1863932259058794'
  R2: '0.7248905188972558'
  RMSE: '1.4441995557271539'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size: 1024
  layers: 1
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: true
10-fold cross-validation results:
  MAE: '1.1863932259058794'
  R2: '0.7248905188972558'
  RMSE: '1.4441995557271539'
args:
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  hidden_size: 1024
  layers: 2
  lr: 0.0277
  max_epochs: 100
  random_state: 0
  transfer_learning: true
