args: !!python/object:argparse.Namespace
  batch_size: 64
  csv_file: null
  data_path: null
  debug: false
  delta_ML: false
  dropout: 0.0
  ensemble_size: 4
  features:
  - mol1_hidden
  - rad1_hidden
  - mol2_hidden
  - rad2_hidden
  - rad_atom1_hidden
  - rad_atom2_hidden
  gpu: true
  hidden_size: 1024
  host: 127.0.0.1
  k_fold: 10
  layers: 2
  learning_rate: 0.0277
  lr_ratio: 0.95
  max_epochs: 100
  mode: client
  port: 57546
  pred_file: null
  random_state: 0
  rxn_id_column: rxn_id
  sample: null
  save_dir: tmp/cv_omega_60test
  splits:
  - 80
  - 10
  - 10
  target_column: G_act
  test_set_path: tmp/omega_data/test_set.pkl
  train_valid_set_path: tmp/omega_data/train_valid_set.pkl
  trained_dir: tmp/cv_in-house_data/fold_0
  transfer_learning: true
test_metrics:
  test_loss: 0.292758584022522
